export const heroLegend = {
  'aa': "Ancient Apparition",
  'alch': "Alchemist",
  'am': "Anti-Mage",
  'arc': "Arc Warden",
  'axe': "Axe",
  'bat': "Batrider",
  'bb': "Bristleback",
  'beast': "Beastmaster",
  'bh': "Bounty Hunter",
  'blood': "Bloodseeker",
  'brew': "Brewmaster",
  'centaur': "Centaur Warrunner",
  'clock': "Clockwerk",
  'cm': "Crystal Maiden",
  'dawnbreaker': "Dawnbreaker",
  'disruptor': "Disruptor",
  'dk': "Dragon Knight",
  'doom': "Doom",
  'dp': "Death Prophet",
  'drow': "Drow Ranger",
  'ds': "Dark Seer",
  'ember': "Ember Spirit",
  'enigma': "Enigma",
  'es': "Earth Spirit",
  'faceless': "Faceless Void",
  'grim': "Grimstroke",
  'gyro': "Gyrocopter",
  'hoodwink': "Hoodwink",
  'huskar': "Huskar",
  'invoker': "Invoker",
  'io': "Io",
  'jakiro': "Jakiro",
  'jugg': "Juggernaut",
  'kka': "Kunkka",
  'kotl': "Keeper of the Light",
  'lc': "Legion Commander",
  'lesh': "Leshrac",
  'lich': "Lich",
  'lina': "Lina",
  'lion': "Lion",
  'luna': "Luna",
  'magnus': "Magnus",
  'mars': "Mars",
  'medusa': "Medusa",
  'mirana': "Mirana",
  'mk': "Monkey King",
  'morph': "Morphling",
  'naga': "Naga Siren",
  'naix': "Lifestealer",
  'necro': "Necrophos",
  'ns': "Night Stalker",
  'nyx': "Nyx Assassin",
  'od': "Outworld Devourer",
  "ogre": "Ogre Magi",
  'omni': "Omniknight",
  "oracle": "Oracle",
  'pa': "Phantom Assassin",
  'pango': "Pangolier",
  'phoenix': "Phoenix",
  'pl': "Phantom Lancer",
  'puck': "Puck",
  'pudge': "Pudge",
  'pugna': "Pugna",
  'qop': "Queen of Pain",
  'razor': "Razor",
  'riki': "Riki",
  'rubick': "Rubick",
  'sd': "Shadow Demon",
  'sf': "Shadow Fiend",
  'shaker': "Earthshaker",
  'shaman': "Shadow Shaman",
  'silencer': "Silencer",
  'sk': "Sand King",
  'sky': "Skywrath Mage",
  'slardar': "Slardar",
  'slark': "Slark",
  'snap': "Snapfire",
  'sniper': "Sniper",
  'spectre': "Spectre",
  'storm': "Storm Spirit",
  'sven': "Sven",
  'tb': "Terrorblade",
  'tide': "Tidehunter",
  'timber': "Timbersaw",
  'tinker': "Tinker",
  'tiny': "Tiny",
  'troll': "Troll Warlord",
  'tusk': "Tusk",
  'underlord': "Underlord",
  'undying': "Undying",
  'ursa': "Ursa",
  'viper': "Viper",
  'vs': "Void Spirit",
  'warlock': "Warlock",
  'weaver': "Weaver",
  'wd': "Witch Doctor",
  'willow': "Dark Willow",
  'wk': "Wraith King",
  'wr': "Windranger",
  'ww': "Winter Wyvern",
  'zeus': "Zeus",
}