export const heroLegend = {
  'aa': "Ancient Apparition",
  'alch': "Alchemist",
  'am': "Anti-Mage",
  'arc': "Arc Warden",
  'axe': "Axe",
  'bat': "Batrider",
  'bb': "Bristleback",
  'beast': "Beastmaster",
  'bh': "Bounty Hunter",
  'blood': "Bloodseeker",
  'brew': "Brewmaster",
  'centaur': "Centaur Warrunner",
  'clock': "Clockwerk",
  'cm': "Crystal Maiden",
  'dawnbreaker': "Dawnbreaker",
  'dazzle': "Dazzle",
  'disruptor': "Disruptor",
  'dk': "Dragon Knight",
  'doom': "Doom",
  'dp': "Death Prophet",
  'drow': "Drow Ranger",
  'ds': "Dark Seer",
  'ember': "Ember Spirit",
  'enigma': "Enigma",
  'es': "Earth Spirit",
  'faceless': "Faceless Void",
  'grim': "Grimstroke",
  'gyro': "Gyrocopter",
  'hoodwink': "Hoodwink",
  'huskar': "Huskar",
  'invoker': "Invoker",
  'io': "Io",
  'jakiro': "Jakiro",
  'jugg': "Juggernaut",
  'kka': "Kunkka",
  'kotl': "Keeper of the Light",
  'lc': "Legion Commander",
  'lesh': "Leshrac",
  'lich': "Lich",
  'lina': "Lina",
  'lion': "Lion",
  'luna': "Luna",
  'magnus': "Magnus",
  'mars': "Mars",
  'medusa': "Medusa",
  'mirana': "Mirana",
  'mk': "Monkey King",
  'morph': "Morphling",
  'naga': "Naga Siren",
  'naix': "Lifestealer",
  'necro': "Necrophos",
  'ns': "Night Stalker",
  'nyx': "Nyx Assassin",
  'od': "Outworld Devourer",
  "ogre": "Ogre Magi",
  'omni': "Omniknight",
  "oracle": "Oracle",
  'pa': "Phantom Assassin",
  'pango': "Pangolier",
  'phoenix': "Phoenix",
  'pl': "Phantom Lancer",
  'puck': "Puck",
  'pudge': "Pudge",
  'pugna': "Pugna",
  'qop': "Queen of Pain",
  'razor': "Razor",
  'riki': "Riki",
  'rubick': "Rubick",
  'sd': "Shadow Demon",
  'sf': "Shadow Fiend",
  'shaker': "Earthshaker",
  'shaman': "Shadow Shaman",
  'silencer': "Silencer",
  'sk': "Sand King",
  'sky': "Skywrath Mage",
  'slardar': "Slardar",
  'slark': "Slark",
  'snap': "Snapfire",
  'sniper': "Sniper",
  'spectre': "Spectre",
  'storm': "Storm Spirit",
  'sven': "Sven",
  'ta': "Templar Assassin",
  'tb': "Terrorblade",
  'tide': "Tidehunter",
  'timber': "Timbersaw",
  'tinker': "Tinker",
  'tiny': "Tiny",
  'troll': "Troll Warlord",
  'tusk': "Tusk",
  'underlord': "Underlord",
  'undying': "Undying",
  'ursa': "Ursa",
  'viper': "Viper",
  'vs': "Void Spirit",
  'warlock': "Warlock",
  'weaver': "Weaver",
  'wd': "Witch Doctor",
  'willow': "Dark Willow",
  'wk': "Wraith King",
  'wr': "Windranger",
  'ww': "Winter Wyvern",
  'zeus': "Zeus",
}

export const pictureLegend = {
  'aa': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/ancient_apparition_full.png",
  'alch': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/alchemist_full.png",
  'am': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/antimage_full.png",
  'arc': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/arc_warden_full.png",
  'axe': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/axe_full.png",
  'bat': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/batrider_full.png",
  'bb': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/bristleback_full.png",
  'beast': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/beastmaster_full.png",
  'bh': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/bounty_hunter_full.png",
  'blood': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/bloodseeker_full.png",
  'brew': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/brewmaster_full.png",
  'centaur': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/centaur_full.png",
  'clock': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/rattletrap_full.png",
  'cm': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/crystal_maiden_full.png",
  'dawnbreaker': "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/dawnbreaker.png",
  'dazzle': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/dazzle_full.png",
  'disruptor': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/disruptor_full.png",
  'dk': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/dragon_knight_full.png",
  'doom': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/doom_bringer_full.png",
  'dp': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/death_prophet_full.png",
  'drow': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/drow_ranger_full.png",
  'ds': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/dark_seer_full.png",
  'ember': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/ember_spirit_full.png",
  'enigma': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/enigma_full.png",
  'es': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/earth_spirit_full.png",
  'faceless': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/faceless_void_full.png",
  'grim': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/grimstroke_full.png",
  'gyro': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/gyrocopter_full.png",
  'hoodwink': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/hoodwink_full.png",
  'huskar': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/huskar_full.png",
  'invoker': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/invoker_full.png",
  'io': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/wisp_full.png",
  'jakiro': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/jakiro_full.png",
  'jugg': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/juggernaut_full.png",
  'kka': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/kunkka_full.png",
  'kotl': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/keeper_of_the_light_full.png",
  'lc': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/legion_commander_full.png",
  'lesh': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/leshrac_full.png",
  'lich': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/lich_full.png",
  'lina': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/lina_full.png",
  'lion': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/lion_full.png",
  'luna': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/luna_full.png",
  'magnus': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/magnataur_full.png",
  'mars': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/mars_full.png",
  'medusa': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/medusa_full.png",
  'mirana': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/mirana_full.png",
  'mk': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/monkey_king_full.png",
  'morph': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/morphling_full.png",
  'naga': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/naga_siren_full.png",
  'naix': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/life_stealer_full.png",
  'necro': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/necrolyte_full.png",
  'ns': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/night_stalker_full.png",
  'nyx': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/nyx_assassin_full.png",
  'od': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/obsidian_destroyer_full.png",
  "ogre": "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/ogre_magi_full.png",
  'omni': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/omniknight_full.png",
  "oracle": "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/oracle_full.png",
  'pa': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/phantom_assassin_full.png",
  'pango': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/pangolier_full.png",
  'phoenix': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/phoenix_full.png",
  'pl': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/phantom_lancer_full.png",
  'puck': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/puck_full.png",
  'pudge': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/pudge_full.png",
  'pugna': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/pugna_full.png",
  'qop': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/queenofpain_full.png",
  'razor': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/razor_full.png",
  'riki': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/riki_full.png",
  'rubick': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/rubick_full.png",
  'sd': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/shadow_demon_full.png",
  'sf': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/nevermore_full.png",
  'shaker': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/earthshaker_full.png",
  'shaman': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/shadow_shaman_full.png",
  'silencer': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/silencer_full.png",
  'sk': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/sand_king_full.png",
  'sky': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/skywrath_mage_full.png",
  'slardar': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/slardar_full.png",
  'slark': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/slark_full.png",
  'snap': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/snapfire_full.png",
  'sniper': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/sniper_full.png",
  'spectre': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/spectre_full.png",
  'storm': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/storm_spirit_full.png",
  'sven': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/sven_full.png",
  'ta': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/templar_assassin_full.png",
  'tb': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/terrorblade_full.png",
  'tide': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/tidehunter_full.png",
  'timber': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/shredder_full.png",
  'tinker': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/tinker_full.png",
  'tiny': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/tiny_full.png",
  'troll': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/troll_warlord_full.png",
  'tusk': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/tusk_full.png",
  'underlord': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/abyssal_underlord_full.png",
  'undying': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/undying_full.png",
  'ursa': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/ursa_full.png",
  'viper': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/viper_full.png",
  'vs': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/void_spirit_full.png",
  'warlock': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/warlock_full.png",
  'weaver': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/weaver_full.png",
  'wd': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/witch_doctor_full.png",
  'willow': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/dark_willow_full.png",
  'wk': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/skeleton_king_full.png",
  'wr': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/windrunner_full.png",
  'ww': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/winter_wyvern_full.png",
  'zeus': "https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/zuus_full.png",
}

export const nameLegend = {
  'Bsu': "BeeSu",
}

export const portraitLegend = {
  'lisa': "/dota-inhouse-stats/angus.png",
  'nanoir': "/dota-inhouse-stats/dixon.png",
  'jeleto': "/dota-inhouse-stats/saif.png",
  'nixnala': "/dota-inhouse-stats/alan.png",
  'geese': "/dota-inhouse-stats/holden.png",
  'coolgav': "/dota-inhouse-stats/gavin.png",
  'pain peko': "/dota-inhouse-stats/denzel.png",
  'justin': "/dota-inhouse-stats/justin.png",
  'lester': "/dota-inhouse-stats/lester.png",
  'monta': "/dota-inhouse-stats/isaac.png",
  'dream': "/dota-inhouse-stats/alex.png",
  'bsu': "/dota-inhouse-stats/bronson.png",
  'chesticlez': "/dota-inhouse-stats/cheston.png",
  'yoshioka': "/dota-inhouse-stats/anthony.png",
  'remia': "/dota-inhouse-stats/huy.png",
}